version: "3.5"
services:

  motioneye:
    image: ccrisan/motioneye:master-armhf # armhf/amd64
    ports:
      - "18765:8765"    # web admin port mapping
    #   - "8081:8081" # local mjpeg streaming port
    volumes:
      - "./conf:/etc/motioneye"
      - "./camera:/var/lib/motioneye"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    hostname: motioneye
    devices:
      - '/dev/vchiq'    # RPI local MMAL camera
    #   - '/dev/video0'
    environment:
        TZ: "Europe/Budapest"
# volumes:
#   conf:
#   camera:
#   /etc/localtime:
