version: "3.5"
services:

  motioneye:
    image: ccrisan/motioneye:master-armhf # OR armhf/amd64
    ports:
      - "18765:8765"    # web admin port mapping
    #   - "8081:8081" # local mjpeg streaming port if you need one
    volumes:
      - "./conf:/etc/motioneye"
      - "./camera:/var/lib/motioneye"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    hostname: motioneye
    devices:
      # - '/dev/vchiq'    # RPI local MMAL camera
      - '/dev/video0' # USB camera
    environment:
        TZ: "Europe/Budapest"
